### ISSUE TITLE
Diplomacy.py is a long file

### ISSUE THREAD

**Issue by trozware** [jackreichelt/Diplomacy#2]
I am not sure how Python handles linked files, but you are sticking multiple class definitions into a single file that is getting very long. My understanding is that it is better style to break up such large files to make for easier collaboration and faster compilations.

**Comment by jackreichelt** [comment]
Diplomacy.py shortened by moving orders out. I'm going to also look into moving the unit tests out to their own file, which will pull it back to ~300 lines.

**Comment by trozware** [comment]
I think moving the unit tests to their own files is a very good idea as they do not need to be part of any built app.

**Comment by jackreichelt** [comment]
Tests split out into a different file. Diplomacy now 293 lines.
